name: flutter_getx_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  dio: ^5.4.3
  retrofit: ^4.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
   # ... 其他 dev_dependencies
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
